### PR TITLE
[swisspush/apikana#20] Add handling for new apikana argument 'useLeadingSlashes'.

### PR DESCRIPTION
**Pull request by hiddenalpha**
This handles new apikana parameter introduced in swisspush/apikana#21.

### CODE REVIEW

**Comment by hiddenalpha** [comment]
This handles new apikana parameter introduced in swisspush/apikana#21.

**Comment by lbovet** [comment]
Hmm. The default must be with leading slash.
So the option should be to remove the leading slash: --noLeadingSlash.
Or better, the option should be actually a prefix: 
```
--generatedPathPrefix=/       # default
--generatedPathPrefix=        # no slash
--generatedPathPrefix=http://blabla  
```
wdyt?

**Comment by nidi3** [comment]
api.yaml has the fields `host` and `basePath` .
What about `if basePath.endsWith('/') pathWithoutSlash else pathWithSlash`?
Optionally a new parameter `baseUrl`could be added to overwrite `host` and `basePath`.

**Comment by hiddenalpha** [comment]
Hmm. Could be a solution too.

**Comment by lbovet** [comment]
The prefix approach is my preferred one. 
BTW, I agree with your point on double negative.

**Comment by lbovet** [comment]
Sorry, I missed your comment, Nidi.
Your solution is even better. It is completely consistent this way.

**Comment by hiddenalpha** [comment]
Ready to review :) (@nidi3, @lbovet)

**Pull request merged**
